version: '3.8'

services:
  postgresql:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
      - POSTGRES_DB=temporal
    ports:
      - 5432:5432

  elasticsearch:
    image: opensearch:1.3.0
    environment:
      - cluster.name=temporal
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms100m -Xmx100m
    ports:
      - 9200:9200

  temporal:
    image: temporalio/auto-setup:1.20.0
    depends_on:
      - postgresql
      - elasticsearch
    environment:
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development.yaml
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
    ports:
      - 7233:7233
      - 7234:7234
      - 7235:7235
      - 7239:7239

  temporal-web:
    image: temporalio/web:1.15.0
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    depends_on:
      - temporal
    ports:
      - 8088:8088

networks:
  temporal-network:
    driver: bridge 